<div class="footer-top__wrapper">
        <div class="container">
            <div class="footer-top">
                <h2 class="footer-top__title">Service & contact</h2>
                <ul class="footer-top__items">
                    <li class="footer-top__item">
                        <img class="footer-top__item-icon" src="<?= $block->getViewFileUrl('images/footer-user-icon.svg'); ?>" alt="footer user icon">
                        <div class="footer-top__item-text">
                            <p class="footer-top__item-name">Arrange quickly in your account</p>
                            <p class="footer-top__item-desc">
                                <a class="footer-top__item-link" href="#">Track your order</a> ,
                                <a class="footer-top__item-link" href="#">pay invoices</a> or
                                <a class="footer-top__item-link" href="#">return an item</a>.
                            </p>
                        </div>
                    </li>
                    <li class="footer-top__item">
                        <img class="footer-top__item-icon" src="<?= $block->getViewFileUrl('images/footer-contact-icon.svg'); ?>" alt="footer contact icon">
                        <div class="footer-top__item-text">
                            <p class="footer-top__item-name">Do you need us?</p>
                            <p class="footer-top__item-desc">
                                We are happy to help you.
                                <a class="footer-top__item-link" href="#">Our customer service</a>
                                is open day and night.
                            </p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
</div>


