<div class="container">
    <div class="header-top">
        <a class="header-top__promotion" href="#">
            <ul class="header-top__list">
                <li class="header-top__item">
                    <strong>Gratis</strong>
                    verzending vanaf 20,-
                </li>
                <li class="header-top__item">
                    Bezorging dezelfde dag, 's avonds of in het weekend*
                </li>
                <li class="header-top__item">
                    <strong>Gratis</strong>
                    retourneren
                </li>
            </ul>
        </a>
        <a class="header-top__select" href="#">
            <strong>Select</strong>
            Ontdek nu de 4 voordelen
        </a>
    </div>
</div>
