<div class="container">
    <div class="header-top">
        <a class="header-top__promotion" href="#">
            <ul class="header-top__list">
                <li class="header-top__item">
                    <strong><?= __('Free') ?></strong>
                    <?= __('shipping from 20,-') ?>
                </li>
                <li class="header-top__item">
                    <?= __('Same day, evening or weekend delivery*') ?>
                </li>
                <li class="header-top__item">
                    <strong><?= __('Free') ?></strong>
                    <?= __('return') ?>
                </li>
            </ul>
        </a>
        <a class="header-top__select" href="#">
            <strong><?= __('Select') ?></strong>
            <?= __('Discover the 4 advantages now') ?>
        </a>
    </div>
</div>
