<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */

use Magento\Framework\App\Action\Action;

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */

// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';

    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    ?>
    <?= /* @noEscape */
    '<!-- ' . $image . '-->' ?>
    <div class="products-widget__wrapper">
        <ul class="products-widget__items">
            <?php $iterator = 1; ?>
            <?php foreach ($items as $_item): ?>
                <?= /* @noEscape */
                ($iterator++ == 1) ? '<li class="products-widget__item">' : '</li><li class="products-widget__item">' ?>
                <?php if ($showWishlist): ?>
                    <div class="products-widget__item-wishlist" data-role="add-to-links">
                        <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                            <a href="#" class="products-widget__item-wishlist-link"
                               data-post='<?= /* @noEscape */
                               $block->getAddToWishlistParams($_item) ?>' data-action="add-to-wishlist"
                               title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                <svg version="1.1" viewBox="0 0 24 24" aria-hidden="true"
                                     class="svg-inline--bi bi-heart-vi bi-lg" data-test="icon-heart-vi" height="35px"
                                     width="35px">
                                    <path d="M12 23.2l-.6-.4C3.5 17.2 0 12.9 0 9c0-3.5 2-6.7 4.9-7.9C7.3.2 9.8.7 12 2.6 14.2.7 16.7.2 19.1 1.1 22 2.3 24 5.5 24 9c0 3.9-3.5 8.2-11.4 13.8l-.6.4zM7.3 2.7c-.6 0-1.1.1-1.6.3C3.6 3.8 2 6.4 2 9c0 3 3.3 6.9 10 11.8C18.7 15.9 22 12 22 9c0-2.6-1.6-5.2-3.7-6-1.8-.7-3.8-.2-5.6 1.7l-.7.7-.7-.7c-1.3-1.3-2.7-2-4-2z"></path>
                                </svg>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="products-widget__item-pic">
                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <h4 class="products-widget__item-name">
                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                       class="products-widget__item-link">
                        <?= $block->escapeHtml($_item->getName()) ?>
                    </a>
                </h4>
                <?= $block->getProductPriceHtml($_item, $type) ?>
                <?= $block->getProductSpecialPriceHtml($_item, $type) ?>
                <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
            <?php endforeach ?>
        </ul>
    </div>
    <?= $block->getPagerHtml() ?>
    <?php if ($block->getBlockHtml('formkey')): ?>
<script type="text/x-magento-init">
    {
        ".block.widget [data-role=tocart-form]": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
    <?php endif; ?>
<?php endif; ?>
