<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Tri')) ?></label>
    <a class="sorter-btn-info" type="button">
        <svg viewBox="0 0 14 14" width="18px" height="18px" fill="@title-dark">
            <path fill-rule="evenodd" d="M7 14A7 7 0 117 0a7 7 0 010 14zm-.033-1a6 6 0 100-12 6 6 0 000 12zm-.464-6.984a.512.512 0 01.509-.516h-.024c.283 0 .514.228.515.516l.027 3.968a.512.512 0 01-.509.516h.024a.516.516 0 01-.515-.516l-.027-3.968zM7.031 4.5a.5.5 0 110-1 .5.5 0 010 1z"></path>
        </svg>
    </a>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
                >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>

<div class="sorter-info__wrapper" id="modal-sorter-info">
    <button class="langs__list-close-btn" id="langs-close-btn" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "toggleContainers": "#modal-langs, #langs-overlay"}}'>&times;</button>
    <h3 class="sorter-info__title">Affichage et présentation</h3>
    <p class="sorter-info__desc">
        Un même article est souvent proposé par plusieurs vendeurs. Chaque recherche affiche le vendeur qui présente le meilleur score en matière de livraison, de prix et de prestations. Par défaut, nous présentons aussi les articles par ordre de popularité, mais ceci est modifiable:
    </p>
    <ul class="sorter-info__items">
        <li class="sorter-info__item">
            <p class="sorter-info__item-title">Pertinence par rapport à vos mots-clés</p>
            <p class="sorter-info__item-text">
                Nous regardons pour ce faire le titre et la description des produits, mais aussi leur popularité et leur disponibilité. Des articles sponsorisés* peuvent également apparaître dans les résultats.
            </p>
        </li>
        <li class="sorter-info__item">
            <p class="sorter-info__item-title">Prix</p>
            <p class="sorter-info__item-text">
                Affiché de façon croissante ou décroissante.
            </p>
        </li>
        <li class="sorter-info__item">
            <p class="sorter-info__item-title">Nouveau sur bol.com</p>
            <p class="sorter-info__item-text">
                Les nouveautés sont mises en avant.
            </p>
        </li>
        <li class="sorter-info__item">
            <p class="sorter-info__item-title">Évaluation</p>
            <p class="sorter-info__item-text">
                Les articles les mieux notés sont affichés en premier. Par article, nous regardons le score obtenu, le nombre d’avis et leur actualité.
            </p>
        </li>
        <li class="sorter-info__item">
            <p class="sorter-info__item-title">Les plus ajoutés aux favoris</p>
            <p class="sorter-info__item-text">
                Le positionnement est proportionnel au nombre de sauvegardes.
            </p>
        </li>
    </ul>


    <div id="langs-overlay" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "", "toggleContainers": "#modal-langs, #langs-overlay"}}'></div>
</div>
