<?php
/**
 * Copyright © Elogic. All rights reserved.
 * See https://elogic.co for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Tri')) ?></label>
    <a class="sorter-btn-info" id="sorter-open-btn" type="button" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "toggleContainers": "#modal-sorter-info, #sorter-overlay"}}'>
        <svg viewBox="0 0 14 14" width="18px" height="18px" fill="@title-dark">
            <path fill-rule="evenodd" d="M7 14A7 7 0 117 0a7 7 0 010 14zm-.033-1a6 6 0 100-12 6 6 0 000 12zm-.464-6.984a.512.512 0 01.509-.516h-.024c.283 0 .514.228.515.516l.027 3.968a.512.512 0 01-.509.516h.024a.516.516 0 01-.515-.516l-.027-3.968zM7.031 4.5a.5.5 0 110-1 .5.5 0 010 1z"></path>
        </svg>
    </a>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php endif; ?>
    <div class="langs__list-wrapper sorter-info" id="modal-sorter-info">
        <button class="langs__list-close-btn" id="langs-close-btn" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "toggleContainers": "#modal-sorter-info, #sorter-overlay"}}'>&times;</button>
        <h3 class="sorter-info__title"><?= __('How sorting works') ?></h3>
        <p class="sorter-info__desc">
            <?= __('Items often have multiple sellers. For each search result, you will see the seller who scores best on delivery promise, price and performance score. In addition, we sort all results by popularity by default, but you can also sort these yourself:') ?>
        </p>
        <ul class="sorter-info__items">
            <li class="sorter-info__item">
                <p class="sorter-info__item-title"><?= __('Popularity of the articles') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('To do this, we look at how much interest there is in an article in different ways. Sponsored articles* may also appear among the results.') ?>
                </p>
            </li>
            <li class="sorter-info__item">
                <p class="sorter-info__item-title"><?= __('Price') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('From low to high or from high to low.') ?>
                </p>
            </li>
            <li class="sorter-info__item">
                <p class="sorter-info__item-title"><?= __('New on bol.com') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('What\'s new on bol.com is at the top.') ?>
                </p>
            </li>
            <li class="sorter-info__item">
                <p class="sorter-info__item-title"><?= __('Rating') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('Articles with the best reviews come first. We check per article what the score is, how many reviews there are and how new the reviews are.') ?>
                </p>
            </li>
            <li class="sorter-info__item">
                <p class="sorter-info__item-title"><?= __('Most wanted on wishlists') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('The more often saved, the higher it ranks.') ?>
                </p>
            </li>

            <li class="sorter-info__item sorter-info__item--last">
                <p class="sorter-info__item-title"><?= __('* What are Sponsored Articles?') ?></p>
                <p class="sorter-info__item-text">
                    <?= __('Sellers can make an article stand out more for a fee. It is then higher among the results.') ?>
                </p>
            </li>
        </ul>
    </div>
    <div id="sorter-overlay" data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active", "baseToggleClass": "", "toggleContainers": "#modal-sorter-info, #sorter-overlay"}}'></div>
</div>
